### ISSUE TITLE
Update Kitty Giraudel's name

### ISSUE THREAD

**Issue by angeliquejw** [josephrexme/josephrex.me#2]
Hi, Joseph! It looks like you have a handful of blog posts ([see here](https://github.com/josephrexme/josephrex.me/search?q=hugo+giraudel)) that reference a previous name for Kitty Giraudel. Would you consider updating those references and links?

I considered making a PR, but somehow directly editing your blog posts felt awkward. Happy to make the PR if you prefer 👍🏻

**Comment by josephrexme** [comment]
Feel free to make a PR @angeliquejw . Sorry it's taking so long to see this

**Comment by josephrexme** [comment]
I'm currently working on migrating my blog from hugo (the static site generator) to eleventy and I've made the changes in new content so there might be no need for a PR here as the new site design should have the changes

**Comment by angeliquejw** [comment]
As someone who also is blogging via Eleventy, this is an extra great update to see, @josephrexme  😄

**Comment by josephrexme** [comment]
Thanks @angeliquejw . The new eleventy version is deployed. Although the old one with the old name is still at https://v4.josephrex.me so it might still get indexed. I'll try to add a robots.txt file there to prevent that
